In [6]:
!pip install flask_restful




In [71]:
from flask import Flask, jsonify, request, Response
from flask_restful import Resource, Api, reqparse
import numpy as np
import pandas as pd

In [ ]:

app = Flask(__name__)
api = Api(app)

ques = {
    1:
        {
            "Strong Structure":
                {
                    "que": "Is the structure strong? ",
                    "options": ["True", "False"],
                    "Path": {
                        "True":"https://www.hometipsor.com/wp-content/uploads/2020/06/how-to-choose-scaffolding-company-1024x768.jpg",
                        "False":"https://i2-prod.mirror.co.uk/incoming/article620423.ece/ALTERNATES/s615b/000F3554-B556-143C-A0080C01AC1BF814.jpg"
                    }
                },
            "Type" : "Radio"
        },
    2:
        {
            "Support":
                {
                    "que": "Is there strong support for the scaffolding?",
                    "options": ["True", "False"],
                     "Path": {
                        "True":"https://elcosh.org/record/document/803/11.gif",
                        "False":"https://elcosh.org/record/document/803/11.gif"
                    }
                },
        "Type" : "Radio"     
        },
    3:
        {
            "Tightly Planked":
                {
                    "que": "Is the scaffolding tightly planked? ",
                    "options": ["True", "False"],
                     "Path": {
                        "True":"https://images.infobloom.com/underside-closeup-wooden-platform-in-scaffolding.jpg",
                        "False":"https://www.osha.gov/sites/default/files/2021-03/badsplit003.jpg"
                    }
                },
            "Type" : "Radio"
        },
    4:
        {
            "Wear Proper harness":
                {
                    "que": "Are the workers wearing proper harness? ",
                    "options": ["True", "False"],
                     "Path": {
                        "True":"https://beautyharmonylife.com/wp-content/uploads/2017/01/Scaffolding-1.gif",
                        "False":"https://beautyharmonylife.com/wp-content/uploads/2017/01/Scaffolding-1.gif"
                    }
                },
        "Type" : "Radio"
        },
    5:
        {
            "Distance from electric line > 10 m":
                {
                    "que": "Is the distance from electric line greater than 10m? ",
                    "options": ["True", "False"],
                     "Path": {
                      #  "True":
                       # "False":
                    }
                },
        "Type" : "Radio"
        },
    6:
        {
            "Base/Landing Surface":
                {
                    "que": "Is the base/landing surface smooth? ",
                    "options": ["True", "False"],
                     "Path": {
                       # "True":
                        #"False":
                    }
                },
        "Type" : "Radio"
        },
    7:
        {
            "Proper PPE kits":
                {
                    "que": "Are the workers wearing proper PPE kits? ",
                    "options": ["True", "False"],
                    "Path": {
                        "True":"https://5.imimg.com/data5/SELLER/Default/2020/9/NF/BA/NB/53900542/ppes-jpg-500x500.jpg",
                        "False":"https://thumbs.dreamstime.com/z/construction-worker-hard-hat-isolated-white-humorous-image-happy-wearing-high-vis-jacket-35049978.jpg"
                    }
                },
        "Type" : "Radio"
        },
    8:
        {
            "Training to workers":
                {
                    "que": "Are the workers properly trained with the safety protocols and methods? ",
                    "options": ["True", "False"],
                    "Path": {
                        "True":"https://www.hseblog.com/wp-content/uploads/2018/05/Construction-Safety-Officer-Training.jpg"
                       # "False":"
                    }
                },
        "Type" : "Radio"
        },
    9:
        {
            "Toeboard":
                {
                    "que": "Are there toeboards,midrail and guardrail present?",
                    "options": ["True", "False"],
                    "Path": {
                        "True":"https://rlsdhamal.com/wp-content/uploads/2019/11/Toe-board.png"
                       # "False":
                    }
                },
        "Type" : "Radio"
        }
}

fet_name = list()
input_fet = {}

class Scaffolding(Resource):
    def post(self):
        parser = reqparse.RequestParser()
        parser.add_argument('question', required = True, type = int)
        parser.add_argument('answer', required = False, type = int)
        args = parser.parse_args()

        if args['answer'] is not None:
            input_fet[fet_name[args['question']]] = args['answer']

        if len(list(input_fet.keys())) == len(fet_name):
            output_dict = {'Status':1,'Prediction':predict_(input_fet)}
            input_fet.clear()
            return output_dict
        else:
            if args['answer'] is not None:
                output_dict = {'Status':0, fet_name[args['question'] + 1] : ques[fet_name[args['question'] + 1]]}
                try:
                    output_dict['Answer'] = input_fet[fet_name[args['question'] + 1]]
                except:
                    output_dict['Answer'] = 'Not answered'
            else:
                output_dict = {'Status':0, fet_name[args['question']] : ques[fet_name[args['question']]]}
                try:
                    output_dict['Answer'] = input_fet[fet_name[args['question']]]
                except:
                    output_dict['Answer'] = 'Not answered'
            return output_dict
    #@app.route('/answers',methods = ['POST'])
    #def out():

api.add_resource(Scaffolding, '/Scaffolding/')
    

if __name__ == '__main__':
    app.run(debug=False)


 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [22/Mar/2022 16:55:50] "POST /Scaffolding?question=1&answer=1 HTTP/1.1" 308 -
[2022-03-22 16:55:50,470] ERROR in app: Exception on /Scaffolding/ [POST]
Traceback (most recent call last):
  File "C:\Users\acer\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\acer\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\acer\anaconda3\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\acer\anaconda3\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\acer\anaconda3\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\acer\AppData\Local

In [31]:
questions

{1: {'Strong Structure': {'que': 'Is the structure strong? ',
   'options': ['True', 'False']}},
 2: {'Support': {'que': 'Is there strong support for the scaffolding?',
   'options': ['True', 'False']}},
 3: {'Tightly Planked': {'que': 'Is the scaffolding tightly planked? ',
   'options': ['True', 'False']}},
 4: {'Wear Proper harness': {'que': 'Are the workers wearing proper harness? ',
   'options': ['True', 'False']},
  'ans': 1},
 5: {'Distance from electric line > 10 m': {'que': 'Is the distance from electric line greater than 10m? ',
   'options': ['True', 'False']}},
 6: {'Base/Landing Surface': {'que': 'Is the base/landing surface smooth? ',
   'options': ['True', 'False']}},
 7: {'Proper PPE kits': {'que': 'Are the workers wearing proper PPE kits? ',
   'options': ['True', 'False']}},
 8: {'Training to workers': {'que': 'Are the workers properly trained with the safety protocols and methods? ',
   'options': ['True', 'False']}},
 9: {'Toeboard': {'que': 'Are there toeboards pr

In [7]:
questions['Training to workers']['que']

'Are the workers properly trained with the safety protocols and methods? '

In [43]:
import pickle

In [44]:
model = pickle.load(open('model.pkl','rb'))

In [46]:
prediction = model.predict([[0,0,0,0,0,1,1,1,1]])

In [47]:
prediction

array([0], dtype=int64)

In [48]:
model_sever = pickle.load(open('model_sever.pkl','rb'))
model_injury = pickle.load(open('model_injury.pkl','rb'))

In [49]:
predict_two = model_sever.predict([[0,0,0,0,0,1,1,1,1]])
predict_two

array([1], dtype=int64)

In [50]:
predict_three = model_injury.predict([[0,0,0,0,0,1,1,1,1]])
predict_three

array([1], dtype=int64)

In [61]:
print(answers)

{1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1}


In [ ]:
answers.valu